-- Seed data for equipments
-- This file populates the equipments table with initial equipment

-- Insert default equipment
insert into equipments (
  id,
  name,
  category,
  rarity,
  instrument_type,
  base_level,
  base_score_bonus,
  base_accuracy_bonus,
  base_streak_bonus,
  special_effect,
  price,
  upgrade_price,
  icon,
  description
)
values
  -- MANTLES
  (
    'novice-cloak',
    'Novice Cloak',
    'mantle',
    'common',
    null,
    1,
    50,
    5,
    1,
    'Beginner''s Luck: +10% chance for bonus points',
    20,
    15,
    '🧙‍♂️',
    'A simple cloak worn by music students. Provides basic protection and confidence.'
  ),
  (
    'maestro-robe',
    'Maestro''s Robe',
    'mantle',
    'epic',
    null,
    1,
    200,
    15,
    5,
    'Conductor''s Aura: Double streak bonuses',
    80,
    40,
    '👘',
    'An elegant robe worn by master conductors. Radiates musical authority and precision.'
  ),

  -- ADORNMENTS
  (
    'silver-pendant',
    'Silver Music Note Pendant',
    'adornments',
    'rare',
    null,
    1,
    100,
    8,
    2,
    'Perfect Pitch: +5% accuracy on high notes',
    35,
    25,
    '🎵',
    'A beautiful silver pendant shaped like a musical note. Enhances musical intuition.'
  ),
  (
    'golden-metronome',
    'Golden Metronome Charm',
    'adornments',
    'legendary',
    null,
    1,
    300,
    20,
    8,
    'Perfect Timing: Time-based bonuses never expire',
    120,
    60,
    '⏱️',
    'A legendary golden metronome that keeps perfect time. Masters of rhythm covet this charm.'
  ),

  -- UNIVERSAL TOOLS
  (
    'universal-tuner',
    'Astral Pocket Tuner',
    'instruments',
    'common',
    null,
    1,
    120,
    6,
    2,
    'Stellar Resonance: +3% tuning recovery after battles',
    25,
    18,
    '🧭',
    'A compact tuner attuned to every constellation, useful for any instrument path.'
  ),

  -- VIOLIN SETS
  (
    'starter-violin-kit',
    'Student Violin Care Kit',
    'instruments',
    'common',
    'violin',
    1,
    140,
    10,
    3,
    'Resin Focus: +5% accuracy on sustained notes',
    30,
    22,
    '🏹',
    'Rosin, spare strings, and a practice mute tailored for new violinists.'
  ),
  (
    'virtuoso-violin-bow',
    'Virtuoso Bow of Starlight',
    'instruments',
    'epic',
    'violin',
    1,
    260,
    20,
    6,
    'Celestial Glide: Perfect notes extend streak windows by 1 beat',
    95,
    55,
    '🌌',
    'Handcrafted bow that leaves shimmering trails with every flourish.'
  ),

  -- VIOLA SETS
  (
    'starter-viola-kit',
    'Student Viola Essentials',
    'instruments',
    'common',
    'viola',
    1,
    135,
    9,
    3,
    'Alto Warmth: +4% score on harmony questions',
    28,
    20,
    '🪄',
    'Balanced bow oil and strings to keep mellow viola tones centered.'
  ),
  (
    'echo-viola-bow',
    'Echo Chamber Viola Bow',
    'instruments',
    'rare',
    'viola',
    1,
    210,
    16,
    5,
    'Resonant Memory: +10% streak retention after misses',
    70,
    40,
    '🎼',
    'Resonates with rich overtones, perfect for alto harmonies.'
  ),

  -- ACOUSTIC GUITAR SETS
  (
    'starter-acoustic_guitar-kit',
    'Campfire Acoustic Pack',
    'instruments',
    'common',
    'acoustic_guitar',
    1,
    150,
    11,
    3,
    'Chord Memory: +4% accuracy on chord identification',
    32,
    24,
    '🔥',
    'Picks, capo, and humidifier to keep acoustic sessions glowing.'
  ),
  (
    'acoustic-guitar-sustain-pack',
    'Harmonic Sustain Pack',
    'instruments',
    'rare',
    'acoustic_guitar',
    1,
    220,
    18,
    5,
    'Echo Bloom: Strummed notes grant +8 bonus points on success',
    85,
    48,
    '🌿',
    'Bridge upgrades and coated strings that keep chords ringing longer.'
  ),

  -- ELECTRIC GUITAR SETS
  (
    'starter-electric_guitar-kit',
    'Starter Effects Pedalboard',
    'instruments',
    'common',
    'electric_guitar',
    1,
    155,
    12,
    3,
    'Signal Boost: +5% score on rapid-fire note battles',
    34,
    26,
    '🎛️',
    'Compact multi-effects unit tuned for early shredders.'
  ),
  (
    'electric-guitar-effects-pack',
    'Arc Surge Effects Pack',
    'instruments',
    'epic',
    'electric_guitar',
    1,
    270,
    22,
    6,
    'Thunder Chain: Perfect streaks add +12% score multiplier',
    105,
    58,
    '⚡',
    'Premium pedals and cables forged for electric virtuosos.'
  ),

  -- BASS SETS
  (
    'starter-bass-kit',
    'Foundation Bass Pack',
    'instruments',
    'common',
    'bass',
    1,
    145,
    9,
    3,
    'Groove Anchor: +4% streak stability on rhythm drills',
    30,
    22,
    '🎚️',
    'Flatwound strings and strap locks to lock in supportive lines.'
  ),
  (
    'bass-groove-pack',
    'Deep Resonance Pack',
    'instruments',
    'rare',
    'bass',
    1,
    215,
    17,
    5,
    'Pulse Driver: +9% accuracy on syncopated passages',
    82,
    46,
    '🌊',
    'Preamp and compression tools that keep low-end waves powerful.'
  )
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  rarity = excluded.rarity,
  base_level = excluded.base_level,
  base_score_bonus = excluded.base_score_bonus,
  base_accuracy_bonus = excluded.base_accuracy_bonus,
  base_streak_bonus = excluded.base_streak_bonus,
  special_effect = excluded.special_effect,
  price = excluded.price,
  upgrade_price = excluded.upgrade_price,
  icon = excluded.icon,
  description = excluded.description;

