-- Seed data for instruments
-- This file populates the instruments table with initial instruments

-- Insert default instruments
insert into instruments (
  id, 
  name, 
  type, 
  rarity, 
  base_level,
  base_score_multiplier,
  base_accuracy_bonus, 
  base_streak_bonus, 
  base_tuning,
  price, 
  upgrade_price, 
  tune_price,
  icon, 
  description
)
values
  -- Violin path
  (
    'violin-apprentice',
    'Apprentice Violin',
    'violin',
    'apprentice',
    1,
    1.00,
    0,
    0,
    95,
    0,
    20,
    3,
    '🎻',
    'A reliable student violin tuned for brand-new heroes.'
  ),
  (
    'violin-normal',
    'Journeyman Violin',
    'violin',
    'normal',
    1,
    1.15,
    6,
    1,
    96,
    60,
    40,
    5,
    '🎻',
    'Balanced maple body and richer projection for advancing violinists.'
  ),
  (
    'violin-pro',
    'Virtuoso Violin',
    'violin',
    'pro',
    1,
    1.30,
    12,
    3,
    98,
    120,
    70,
    7,
    '🎻',
    'Hand-carved spruce top with exceptional resonance for stage performers.'
  ),
  (
    'violin-epic',
    'Mythic Violin of Aurora',
    'violin',
    'epic',
    1,
    1.50,
    18,
    5,
    99,
    220,
    110,
    9,
    '🎻',
    'Legendary instrument that sings with prismatic overtones.'
  ),

  -- Viola path
  (
    'viola-apprentice',
    'Apprentice Viola',
    'viola',
    'apprentice',
    1,
    1.00,
    0,
    0,
    94,
    0,
    18,
    3,
    '🪕',
    'Warm-toned viola crafted for foundational technique and tone.'
  ),
  (
    'viola-normal',
    'Studio Viola',
    'viola',
    'normal',
    1,
    1.14,
    5,
    1,
    96,
    55,
    35,
    5,
    '🪕',
    'Responsive strings and mellow projection suited for ensembles.'
  ),
  (
    'viola-pro',
    'Concert Viola',
    'viola',
    'pro',
    1,
    1.28,
    11,
    3,
    98,
    110,
    65,
    7,
    '🪕',
    'Premium tonewoods deliver commanding alto voices on any stage.'
  ),
  (
    'viola-epic',
    'Everbloom Viola',
    'viola',
    'epic',
    1,
    1.47,
    16,
    5,
    99,
    205,
    105,
    9,
    '🪕',
    'Fabled instrument infused with endless resonance and sustain.'
  ),

  -- Acoustic guitar path
  (
    'acoustic_guitar-apprentice',
    'Apprentice Acoustic Guitar',
    'acoustic_guitar',
    'apprentice',
    1,
    1.02,
    2,
    0,
    93,
    0,
    22,
    3,
    '🎸',
    'Spruce-top dreadnought that keeps practice sessions bright and forgiving.'
  ),
  (
    'acoustic_guitar-normal',
    'Session Acoustic Guitar',
    'acoustic_guitar',
    'normal',
    1,
    1.18,
    7,
    1,
    95,
    65,
    38,
    5,
    '🎸',
    'Responsive mid-range presence ideal for open mics and jam circles.'
  ),
  (
    'acoustic_guitar-pro',
    'Luthier Acoustic Guitar',
    'acoustic_guitar',
    'pro',
    1,
    1.32,
    13,
    3,
    97,
    125,
    72,
    7,
    '🎸',
    'Custom craftsmanship with crystalline harmonics and projection.'
  ),
  (
    'acoustic_guitar-epic',
    'Solaris Acoustic Guitar',
    'acoustic_guitar',
    'epic',
    1,
    1.52,
    19,
    5,
    99,
    215,
    112,
    9,
    '🎸',
    'Sun-forged instrument radiating golden chords across any venue.'
  ),

  -- Electric guitar path
  (
    'electric_guitar-apprentice',
    'Apprentice Electric Guitar',
    'electric_guitar',
    'apprentice',
    1,
    1.03,
    3,
    0,
    94,
    0,
    24,
    3,
    '⚡🎸',
    'Lightweight build with forgiving action for first riffs and solos.'
  ),
  (
    'electric_guitar-normal',
    'Stage Electric Guitar',
    'electric_guitar',
    'normal',
    1,
    1.20,
    8,
    1,
    96,
    70,
    42,
    5,
    '⚡🎸',
    'Dual humbuckers deliver reliable punch for rehearsals and shows.'
  ),
  (
    'electric_guitar-pro',
    'Virtuoso Electric Guitar',
    'electric_guitar',
    'pro',
    1,
    1.35,
    14,
    3,
    98,
    135,
    78,
    7,
    '⚡🎸',
    'Premium pickups with liquid sustain for precise technical passages.'
  ),
  (
    'electric_guitar-epic',
    'Stormcaller Electric Guitar',
    'electric_guitar',
    'epic',
    1,
    1.55,
    20,
    5,
    99,
    225,
    120,
    9,
    '⚡🎸',
    'Electrified masterpiece that channels thunder into every lick.'
  ),

  -- Bass path
  (
    'bass-apprentice',
    'Apprentice Bass',
    'bass',
    'apprentice',
    1,
    1.01,
    1,
    0,
    94,
    0,
    20,
    3,
    '🎸🔊',
    'Short-scale bass that keeps grooves steady for newcomers.'
  ),
  (
    'bass-normal',
    'Groove Bass',
    'bass',
    'normal',
    1,
    1.17,
    6,
    1,
    96,
    62,
    36,
    5,
    '🎸🔊',
    'Punchy pickups with articulate lows perfect for band practice.'
  ),
  (
    'bass-pro',
    'Session Bass',
    'bass',
    'pro',
    1,
    1.32,
    12,
    3,
    98,
    130,
    74,
    7,
    '🎸🔊',
    'Professional rig-ready bass with flawless intonation and sustain.'
  ),
  (
    'bass-epic',
    'Abyssal Bass',
    'bass',
    'epic',
    1,
    1.54,
    18,
    5,
    99,
    218,
    118,
    9,
    '🎸🔊',
    'Deep-sea forged bass that summons tidal grooves on demand.'
  )
on conflict (id) do update set
  name = excluded.name,
  type = excluded.type,
  rarity = excluded.rarity,
  base_level = excluded.base_level,
  base_score_multiplier = excluded.base_score_multiplier,
  base_accuracy_bonus = excluded.base_accuracy_bonus,
  base_streak_bonus = excluded.base_streak_bonus,
  base_tuning = excluded.base_tuning,
  price = excluded.price,
  upgrade_price = excluded.upgrade_price,
  tune_price = excluded.tune_price,
  icon = excluded.icon,
  description = excluded.description;

